services:
  storage_tier1:
    build:
      context: ./StorageNode
      dockerfile: Dockerfile.storage
    container_name: storage_tier1
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - tier1_data:/mnt/raw
      - /dev:/dev
    networks:
      - simulation_net
    environment:
      - NETWORK_DELAY=0ms

  storage_tier2:
    build:
      context: ./StorageNode
      dockerfile: Dockerfile.storage
    container_name: storage_tier2
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - tier2_data:/mnt/raw
      - /dev:/dev
    networks:
      - simulation_net
    environment:
      - NETWORK_DELAY=20ms

  storage_tier3:
    build:
      context: ./StorageNode
      dockerfile: Dockerfile.storage
    container_name: storage_tier3
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - tier3_data:/mnt/raw
      - /dev:/dev
    networks:
      - simulation_net
    environment:
      - NETWORK_DELAY=50ms

  file_system_server:
    build:
      context: ./ServerNode/
      dockerfile: Dockerfile.server
    container_name: file_system_server
    privileged: true
    networks:
      - simulation_net
    depends_on:
      - storage_tier1
      - storage_tier2
      - storage_tier3
    volumes:
      - nfs_mounts:/mnt/nfs

volumes:
  tier1_data:
  tier2_data:
  tier3_data:
  nfs_mounts:

networks:
  simulation_net:
    driver: bridge
