FROM alpine:latest

RUN apk update && apk add --no-cache \
  bash \
  nfs-utils \
  iputils \
  tini

COPY entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash

EXPOSE 2049 111

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/entrypoint.bash"]

