FROM alpine:latest

RUN apk update && apk add --no-cache \
    bash \
    nfs-utils \
    rpcbind \
    iproute2 \
    lvm2 \
    util-linux \
    tini

RUN mkdir -p /mnt/raw /mnt/tier

COPY exports /etc/exports

COPY entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash

EXPOSE 2049 111

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/entrypoint.bash"]

